/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Materia;
import java.awt.Graphics;
import java.awt.Image;
import java.util.TreeSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gon_k
 */

public class prueba extends javax.swing.JFrame {

    public static TreeSet<Materia> listaMaterias = new TreeSet<>();

    public void cerrarVentana() {
        String botones[] = {"Cerrar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicación?", "Opción Salir",
                0, 0, null, botones, this);
        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (eleccion == JOptionPane.NO_OPTION) {
            System.out.println("Se canceló el cierre de la aplicación");
        }
    }

    /**
     * Creates new form prueba
     */
    public prueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono= new ImageIcon(getClass().getResource("/recursos/campus2.jpg"));
        Image imagen=icono.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmiFormAlu = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmiFormMat = new javax.swing.JMenuItem();
        jmAdministración = new javax.swing.JMenu();
        jmiManejoInsc = new javax.swing.JMenuItem();
        jmiManiNotas = new javax.swing.JMenuItem();
        jmConsultar = new javax.swing.JMenu();
        jmiAluXMat = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jmAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/alumnos.png"))); // NOI18N

        jmiFormAlu.setText("Formulario de Alumno");
        jmiFormAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormAluActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiFormAlu);

        jMenuBar1.add(jmAlumno);

        jmMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/materias.png"))); // NOI18N

        jmiFormMat.setText("Formulario de Materia");
        jmiFormMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormMatActionPerformed(evt);
            }
        });
        jmMateria.add(jmiFormMat);

        jMenuBar1.add(jmMateria);

        jmAdministración.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/admin.png"))); // NOI18N

        jmiManejoInsc.setText("Manejo de Inscripciones");
        jmiManejoInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManejoInscActionPerformed(evt);
            }
        });
        jmAdministración.add(jmiManejoInsc);

        jmiManiNotas.setText("Manipulación de Notas");
        jmiManiNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManiNotasActionPerformed(evt);
            }
        });
        jmAdministración.add(jmiManiNotas);

        jMenuBar1.add(jmAdministración);

        jmConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/consultas.png"))); // NOI18N

        jmiAluXMat.setText("Alumnos por Materia");
        jmiAluXMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAluXMatActionPerformed(evt);
            }
        });
        jmConsultar.add(jmiAluXMat);

        jMenuBar1.add(jmConsultar);

        jmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/exit.png"))); // NOI18N
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiFormAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormAluActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GestionAlumno ga = new GestionAlumno();
        ga.setVisible(true);
        jDesktopPane1.add(ga);
        jDesktopPane1.moveToFront(ga);
    }//GEN-LAST:event_jmiFormAluActionPerformed


    private void jmiFormMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormMatActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        MateriaVista2 mv = new MateriaVista2();
        mv.setVisible(true);
        jDesktopPane1.add(mv);
        jDesktopPane1.moveToFront(mv);
    }//GEN-LAST:event_jmiFormMatActionPerformed

    private void jmiAluXMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAluXMatActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        AlumnoPorMateria alm = new AlumnoPorMateria();
        alm.setVisible(true);
        jDesktopPane1.add(alm);
        jDesktopPane1.moveToFront(alm);
    }//GEN-LAST:event_jmiAluXMatActionPerformed

    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
       cerrarVentana();
    }//GEN-LAST:event_jmSalirMouseClicked

    private void jmiManejoInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManejoInscActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        InscripcionView iv=new InscripcionView();
        iv.setVisible(true);
        jDesktopPane1.add(iv);
        jDesktopPane1.moveToFront(iv);
    }//GEN-LAST:event_jmiManejoInscActionPerformed

    private void jmiManiNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManiNotasActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        CargaDeNotas cdn=new CargaDeNotas();
        cdn.setVisible(true);
        jDesktopPane1.add(cdn);
        jDesktopPane1.moveToFront(cdn);
    }//GEN-LAST:event_jmiManiNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new prueba().setVisible(true);
                prueba p = new prueba();
                p.setLocationRelativeTo(null);
                p.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdministración;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmConsultar;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAluXMat;
    private javax.swing.JMenuItem jmiFormAlu;
    private javax.swing.JMenuItem jmiFormMat;
    private javax.swing.JMenuItem jmiManejoInsc;
    private javax.swing.JMenuItem jmiManiNotas;
    // End of variables declaration//GEN-END:variables
}
